#!/usr/bin/env bash

linesx () {
  val=$(tput cols)
  x=1
  while [ $x -le $val ]; do
    echo -n ✸
    x=$((x+1));
  done
}

reset
linesx
echo
echo
echo -e "\e[1;32m       Making EPEL workstation for CentOS\e[0m"
echo
linesx
echo

dnf install -y epel-release
dnf install -y ansible tmux iotop nethogs git vim sec clamav-server clamav-data clamav-update clamav-filesystem clamav clamav-scanner-systemd clamav-devel clamav-lib clamav-server-systemd

systemctl disable sec

rpm --import https://packages.wazuh.com/key/GPG-KEY-WAZUH

cat > /etc/yum.repos.d/wazuh.repo <<\EOF
[wazuh_repo]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=Wazuh repository
baseurl=https://packages.wazuh.com/3.x/yum/
protect=1
EOF

dnf install -y wazuh-manager

systemctl enable wazuh-manager

cp clamd.service /etc/systemd/system/clamd.service
cp scan.conf /etc/clamd.d/scan.conf

echo "updating virus database"
echo "if you haven't run a freshclam yet this could take a while, running freshclam now..."
freshclam &&
systemctl enable clamd.service --now && linesx
echo 
echo "Complete."
echo
